### ISSUE TITLE
Accessing a Directory on Removable Media

### ISSUE THREAD

**Issue by fjr619** [googlesamples/android-ScopedDirectoryAccess#4]
In the document : 
"To use Scoped Directory Access to access directories on removable media, first add a BroadcastReceiver that listens for the MEDIA_MOUNTED notification"

i already create CustomReceiver that extends BroadcastReceiver , but i got confuse with onRecieve method, what should i do in that method?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
